### ISSUE TITLE
Generated app uses defaultAction which is not declared

### ISSUE THREAD

**Issue by 3v0k4** [taunus/generator-taunus#1]
Seems like the template is using an old version of Taunus where in render.js you were checking a not declared var defaultAction (in this later commit taunus/taunus@cc11a0942ab118e6ce1e63f1f1168013b142d64e on Taunus changed var from defaultAction to route.action).

I wanted to make a PR and contribute but dunno what version of Taunus you would like to have as a dependency.

![screenshot](https://cloud.githubusercontent.com/assets/5238698/5816512/20875774-a0a1-11e4-934c-38e688a8aea0.png)

**Comment by bevacqua** [comment]
Oops. Thanks. Resolved in `1.2.1` _(just needed to use latest version of `taunus` and `taunus-express`)_
